languageCode = "en-US"
title = "Andrea Severi | Software Engineer"
theme = "awesome-identity"

googleAnalytics = "G-KYQDK321P5"
# Enable generation of `robots.txt` file
enableRobotsTXT = true

## Meta Configurations (HTTP Meta tags & OpenGraph)
[params.meta]
  description = "Andrea Severi, Software Engineer"
  keywords = "andrea, severi, software engineer, developer, java, kotlin, android, rust, jetpack compose, unibo, cesena"
  images = [
    "myself.jpg"
  ]

[params.profile]
  portrait = "myself.jpg"
  firstname = "Andrea"
  lastname = "Severi"
  title = "Computer Science and Engineering student @Unibo"
  bio = """"""

[params.contacts]
  email = "andrea.severi.dev@gmail.com"
  github = "seve-andre"
  linkedin = "andrea-severi"
  instagram = "seve_andre"
  
[[params.actions]]
  name = "read my cv"
  url = "https://github.com/seve-andre/curriculum-vitae"

[params.footer]
  copyright = "© 2023 Andrea Severi. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true

## Privacy Configurations (GDPR)
[privacy]
  [privacy.googleAnalytics]
    disable = false
    # Make the users’ IP addresses are anonymized within Google Analytics
    anonymizeIP = false
    # Make the GA templates respect the “Do Not Track” HTTP header
    respectDoNotTrack = false
    # Disable the use of Cookies and use Session Storage to Store the GA Client ID
    useSessionStorage = false
